---
- name: Install OpenVPN with apt
  apt:
    name: openvpn
    state: latest
  tags:
    - openvpn_setup

- name: Ensure user '{{ openvpn_user }}' exists
  user:
    name: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no
  tags:
    - openvpn_setup
...
